package yahoofinance.model.financials.enums;

public enum FinancialsKey {
	TAX_EFFECT_OF_UNUSUAL_ITEMS("TaxEffectOfUnusualItems"),
	TAX_RATE_FOR_CALCS("TaxRateForCalcs"),
	NORMALIZED_EBITDA("NormalizedEBITDA"),
	NORMALIZED_DILUTED_EPS("NormalizedDilutedEPS"),
	NORMALIZED_BASIC_EPS("NormalizedBasicEPS"),
	TOTAL_UNUSUAL_ITEMS("TotalUnusualItems"),
	TOTAL_UNUSUAL_ITEMS_EXCLUDING_GOODWILL("TotalUnusualItemsExcludingGoodwill"),
	NET_INCOME_FROM_CONTINUING_OPERATION_NET_MINORITY_INTEREST("NetIncomeFromContinuingOperationNetMinorityInterest"),
	RECONCILED_DEPRECIATION("ReconciledDepreciation"),
	RECONCILED_COST_OF_REVENUE("ReconciledCostOfRevenue"),
	EBITDA("EBITDA"),
	EBIT("EBIT"),
	NET_INTEREST_INCOME("NetInterestIncome"),
	INTEREST_EXPENSE("InterestExpense"),
	INTEREST_INCOME("InterestIncome"),
	CONTINUING_AND_DISCONTINUED_DILUTED_EPS("ContinuingAndDiscontinuedDilutedEPS"),
	CONTINUING_AND_DISCONTINUED_BASIC_EPS("ContinuingAndDiscontinuedBasicEPS"),
	NORMALIZED_INCOME("NormalizedIncome"),
	NET_INCOME_FROM_CONTINUING_AND_DISCONTINUED_OPERATION("NetIncomeFromContinuingAndDiscontinuedOperation"),
	TOTAL_EXPENSES("TotalExpenses"),
	RENT_EXPENSE_SUPPLEMENTAL("RentExpenseSupplemental"),
	REPORTED_NORMALIZED_DILUTED_EPS("ReportedNormalizedDilutedEPS"),
	REPORTED_NORMALIZED_BASIC_EPS("ReportedNormalizedBasicEPS"),
	TOTAL_OPERATING_INCOME_AS_REPORTED("TotalOperatingIncomeAsReported"),
	DIVIDEND_PER_SHARE("DividendPerShare"),
	DILUTED_AVERAGE_SHARES("DilutedAverageShares"),
	BASIC_AVERAGE_SHARES("BasicAverageShares"),
	DILUTED_EPS("DilutedEPS"),
	DILUTED_EPS_OTHER_GAINS_LOSSES("DilutedEPSOtherGainsLosses"),
	TAX_LOSS_CARRYFORWARD_DILUTED_EPS("TaxLossCarryforwardDilutedEPS"),
	DILUTED_ACCOUNTING_CHANGE("DilutedAccountingChange"),
	DILUTED_EXTRAORDINARY("DilutedExtraordinary"),
	DILUTED_DISCONTINUOUS_OPERATIONS("DilutedDiscontinuousOperations"),
	DILUTED_CONTINUOUS_OPERATIONS("DilutedContinuousOperations"),
	BASIC_EPS("BasicEPS"),
	BASIC_EPS_OTHER_GAINS_LOSSES("BasicEPSOtherGainsLosses"),
	TAX_LOSS_CARRYFORWARD_BASIC_EPS("TaxLossCarryforwardBasicEPS"),
	BASIC_ACCOUNTING_CHANGE("BasicAccountingChange"),
	BASIC_EXTRAORDINARY("BasicExtraordinary"),
	BASIC_DISCONTINUOUS_OPERATIONS("BasicDiscontinuousOperations"),
	BASIC_CONTINUOUS_OPERATIONS("BasicContinuousOperations"),
	DILUTED_NI_AVAILTO_COM_STOCKHOLDERS("DilutedNIAvailtoComStockholders"),
	AVERAGE_DILUTION_EARNINGS("AverageDilutionEarnings"),
	NET_INCOME_COMMON_STOCKHOLDERS("NetIncomeCommonStockholders"),
	OTHER_UNDER_PREFERRED_STOCK_DIVIDEND("OtherunderPreferredStockDividend"),
	PREFERRED_STOCK_DIVIDENDS("PreferredStockDividends"),
	NET_INCOME("NetIncome"),
	MINORITY_INTERESTS("MinorityInterests"),
	NET_INCOME_INCLUDING_NONCONTROLLING_INTERESTS("NetIncomeIncludingNoncontrollingInterests"),
	NET_INCOME_FROM_TAX_LOSS_CARRYFORWARD("NetIncomeFromTaxLossCarryforward"),
	NET_INCOME_EXTRAORDINARY("NetIncomeExtraordinary"),
	NET_INCOME_DISCONTINUOUS_OPERATIONS("NetIncomeDiscontinuousOperations"),
	NET_INCOME_CONTINUOUS_OPERATIONS("NetIncomeContinuousOperations"),
	EARNINGS_FROM_EQUITY_INTEREST_NET_OF_TAX("EarningsFromEquityInterestNetOfTax"),
	TAX_PROVISION("TaxProvision"),
	PRETAX_INCOME("PretaxIncome"),
	OTHER_INCOME_EXPENSE("OtherIncomeExpense"),
	OTHER_NON_OPERATING_INCOME_EXPENSES("OtherNonOperatingIncomeExpenses"),
	SPECIAL_INCOME_CHARGES("SpecialIncomeCharges"),
	GAIN_ON_SALE_OF_PPE("GainOnSaleOfPPE"),
	GAIN_ON_SALE_OF_BUSINESS("GainOnSaleOfBusiness"),
	OTHER_SPECIAL_CHARGES("OtherSpecialCharges"),
	WRITE_OFF("WriteOff"),
	IMPAIRMENT_OF_CAPITAL_ASSETS("ImpairmentOfCapitalAssets"),
	RESTRUCTURING_AND_MERGERN_ACQUISITION("RestructuringAndMergernAcquisition"),
	SECURITIES_AMORTIZATION("SecuritiesAmortization"),
	EARNINGS_FROM_EQUITY_INTEREST("EarningsFromEquityInterest"),
	GAIN_ON_SALE_OF_SECURITY("GainOnSaleOfSecurity"),
	NET_NON_OPERATING_INTEREST_INCOME_EXPENSE("NetNonOperatingInterestIncomeExpense"),
	TOTAL_OTHER_FINANCE_COST("TotalOtherFinanceCost"),
	INTEREST_EXPENSE_NON_OPERATING("InterestExpenseNonOperating"),
	INTEREST_INCOME_NON_OPERATING("InterestIncomeNonOperating"),
	OPERATING_INCOME("OperatingIncome"),
	OPERATING_EXPENSE("OperatingExpense"),
	OTHER_OPERATING_EXPENSES("OtherOperatingExpenses"),
	OTHER_TAXES("OtherTaxes"),
	PROVISION_FOR_DOUBTFUL_ACCOUNTS("ProvisionForDoubtfulAccounts"),
	DEPRECIATION_AMORTIZATION_DEPLETION_INCOME_STATEMENT("DepreciationAmortizationDepletionIncomeStatement"),
	DEPLETION_INCOME_STATEMENT("DepletionIncomeStatement"),
	DEPRECIATION_AND_AMORTIZATION_IN_INCOME_STATEMENT("DepreciationAndAmortizationInIncomeStatement"),
	AMORTIZATION("Amortization"),
	AMORTIZATION_OF_INTANGIBLES_INCOME_STATEMENT("AmortizationOfIntangiblesIncomeStatement"),
	DEPRECIATION_INCOME_STATEMENT("DepreciationIncomeStatement"),
	RESEARCH_AND_DEVELOPMENT("ResearchAndDevelopment"),
	SELLING_GENERAL_AND_ADMINISTRATION("SellingGeneralAndAdministration"),
	SELLING_AND_MARKETING_EXPENSE("SellingAndMarketingExpense"),
	GENERAL_AND_ADMINISTRATIVE_EXPENSE("GeneralAndAdministrativeExpense"),
	OTHER_GANDA("OtherGandA"),
	INSURANCE_AND_CLAIMS("InsuranceAndClaims"),
	RENT_AND_LANDING_FEES("RentAndLandingFees"),
	SALARIES_AND_WAGES("SalariesAndWages"),
	GROSS_PROFIT("GrossProfit"),
	COST_OF_REVENUE("CostOfRevenue"),
	TOTAL_REVENUE("TotalRevenue"),
	EXCISE_TAXES("ExciseTaxes"),
	OPERATING_REVENUE("OperatingRevenue"),
	LOSS_ADJUSTMENT_EXPENSE("LossAdjustmentExpense"),
	NET_POLICYHOLDER_BENEFITS_AND_CLAIMS("NetPolicyholderBenefitsAndClaims"),
	POLICYHOLDER_BENEFITS_GROSS("PolicyholderBenefitsGross"),
	POLICYHOLDER_BENEFITS_CEDED("PolicyholderBenefitsCeded"),
	OCCUPANCY_AND_EQUIPMENT("OccupancyAndEquipment"),
	PROFESSIONAL_EXPENSE_AND_CONTRACT_SERVICES_EXPENSE("ProfessionalExpenseAndContractServicesExpense"),
	OTHER_NON_INTEREST_EXPENSE("OtherNonInterestExpense");

	private final String value;

	FinancialsKey(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
